export const adminConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETPENDINGCAMPAIGN_REQUEST: 'GETPENDINGCAMPAIGN_REQUEST',
    GETPENDINGCAMPAIGN_SUCCESS: 'GETPENDINGCAMPAIGN_SUCCESS',
    GETPENDINGCAMPAIGN_FAILURE: 'GETPENDINGCAMPAIGN_FAILURE',

    DASHBOARDDETAIL_REQUEST:'DASHBOARDDETAIL_REQUEST',
    DASHBOARDDETAIL_SUCCESS:'DASHBOARDDETAIL_SUCCESS',
    DASHBOARDDETAIL_FAILURE:'DASHBOARDDETAIL_FAILURE',

    ACCEPTED_REQUEST:"ACCEPTED_REQUEST",
    ACCEPTED_SUCCESS:"ACCEPTED_SUCCESS",
    ACCEPTED_FAILURE:"ACCEPTED_FAILURE",

    REJECTED_REQUEST:"REJECTED_REQUEST",
    REJECTED_SUCCESS:"REJECTED_SUCCESS",
    REJECTED_FAILURE:"REJECTED_FAILURE",
    
    USERSDETAILS_REQUEST:"USERSDETAILS_REQUEST",
    USERSDETAILS_SUCCESS:"USERSDETAILS_SUCCESS",
    USERSDETAILS_FAILURE:"USERSDETAILS_FAILURE",

    CAMPAIGNS_REQUEST:"CAMPAIGNS_REQUEST",
    CAMPAIGNS_SUCCESS:"CAMPAIGNS_SUCCESS",
    CAMPAIGNS_FAILURE:"CAMPAIGNS_FAILURE",

    USERDETAILS_REQUEST:"USERDETAILS_REQUEST",
    USERDETAILS_SUCCESS:"USERDETAILS_SUCCESS",
    USERDETAILS_FAILURE:"USERDETAILS_FAILURE",

    CAMPAIGN_GETBYUSERID_REQUEST :"CAMPAIGN_GETBYUSERID_REQUEST",
    CAMPAIGN_GETBYUSERID_SUCCESS :"CAMPAIGN_GETBYUSERID_SUCCESS",
    CAMPAIGN_GETBYUSERID_FAILURE :"CAMPAIGN_GETBYUSERID_FAILURE",

    CAMPAIGN_INVESTED_GETBYUSERID_REQUEST :"CAMPAIGN_INVESTED_GETBYUSERID_REQUEST",
    CAMPAIGN_INVESTED_GETBYUSERID_SUCCESS :"CAMPAIGN_INVESTED_GETBYUSERID_SUCCESS",
    CAMPAIGN_INVESTED_GETBYUSERID_FAILURE :"CAMPAIGN_INVESTED_GETBYUSERID_FAILURE",

    CAMPAIGN_INVESTOR_REQUEST : 'CAMPAIGN_INVESTOR_REQUEST',
    CAMPAIGN_INVESTOR_SUCCESS : 'CAMPAIGN_INVESTOR_SUCCESS',
    CAMPAIGN_INVESTOR_FAILURE : 'CAMPAIGN_INVESTOR_FAILURE',

    MONTHLYREPORT_REQUEST : 'MONTHLYREPORT_REQUEST',
    MONTHLYREPORT_SUCCESS : 'MONTHLYREPORT_SUCCESS',
    MONTHLYREPORT_FAILURE : 'MONTHLYREPORT_FAILURE',
};