export const campaignConstants = {
    CREATE_REQUEST: 'CAMPAIGN_CREATE_REQUEST',
    CREATE_SUCCESS: 'CAMPAIGN_CREATE_SUCCESS',
    CREATE_FAILURE: 'CAMPAIGN_CREATE_FAILURE',

    GETBYID_REQUEST: 'CAMPAIGN_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'CAMPAIGN_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'CAMPAIGN_GETBYID_FAILURE',

    GETBYUSERID_REQUEST: 'CAMPAIGN_GETBYUSERID_REQUEST',
    GETBYUSERID_SUCCESS: 'CAMPAIGN_GETBYUSERID_SUCCESS',
    GETBYUSERID_FAILURE: 'CAMPAIGN_GETBYUSERID_FAILURE',

    VISIT_REQUEST: 'CAMPAIGN_VISIT_REQUEST',
    VISIT_SUCCESS: 'CAMPAIGN_VISIT_SUCCESS',
    VISIT_FAILURE: 'CAMPAIGN_VISIT_FAILURE',

    NEW_CAMPAIGN_REQUEST: 'NEW_CAMPAIGN_REQUEST',
    NEW_CAMPAIGN_SUCCESS: 'NEW_CAMPAIGN_SUCCESS',
    NEW_CAMPAIGN_FAILURE: 'NEW_CAMPAIGN_FAILURE',


    TRENDING_CAMPAIGN_REQUEST: 'TRENDING_CAMPAIGN_REQUEST',
    TRENDING_CAMPAIGN_SUCCESS: 'TRENDING_CAMPAIGN_SUCCESS',
    TRENDING_CAMPAIGN_FAILURE: 'TRENDING_CAMPAIGN_FAILURE',

    GETINVESTEDCAMPAIGN_REQUEST:'GETINVESTEDCAMPAIGN_REQUEST',
    GETINVESTEDCAMPAIGN_SUCCESS:'GETINVESTEDCAMPAIGN_SUCCESS',
    GETINVESTEDCAMPAIGN_FAILURE:'GETINVESTEDCAMPAIGN_FAILURE',

    DELETE_REQUEST: 'CAMPAIGN_DELETE_REQUEST',
    DELETE_SUCCESS: 'CAMPAIGN_DELETE_SUCCESS',
    DELETE_FAILURE: 'CAMPAIGN_DELETE_FAILURE',

    GETBYCATEGORY_SUCCESS: 'GETBYCATEGORY_SUCCESS',
    GETBYCATEGORY_REQUEST: 'GETBYCATEGORY_REQUEST',
    GETBYCATEGORY_FAILURE: 'GETBYCATEGORY_FAILURE',
    
};