export const categoriesConstants = {
    GETALL_REQUEST: 'CATEGORIES_GETALL_REQUEST',
    GETALL_SUCCESS: 'CATEGORIES_GETALL_SUCCESS',
    GETALL_FAILURE: 'CATEGORIES_GETALL_FAILURE',

    TOP_REQUEST: 'CATEGORIES_TOP_REQUEST',
    TOP_SUCCESS: 'CATEGORIES_TOP_SUCCESS',
    TOP_FAILURE: 'CATEGORIES_TOP_FAILURE',
};