export const returnConstants = {
    INVESTOR_REQUEST: 'INVESTOR_REQUEST',
    INVESTOR_SUCCESS: 'INVESTOR_SUCCESS',
    INVESTOR_FAILURE: 'INVESTOR_FAILURE',

    RETURNINVESTMENT_REQUEST :'RETURNINVESTMENT_REQUEST',
    RETURNINVESTMENT_SUCCESS :'RETURNINVESTMENT_SUCCESS',    
    RETURNINVESTMENT_FAILURE :'RETURNINVESTMENT_FAILURE',

};